version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions" # See documentation for possible values
      directory: "/" # Location of package manifests
      schedule:
        interval: "weekly" 
